name: Fisch Season Notifier

on:
  schedule:
    - cron: "0 * * * *"  # chạy mỗi 1 tiếng
  workflow_dispatch:     # cho phép bạn bấm chạy thủ công

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python fisch_notify.py
